// This test was automatically generated by Cut::Output::GmshElementCutTest(), 
// as the cut crashed for this configuration!

#include <iostream>
#include <map>
#include <string>
#include <vector>

#include "cut_test_utils.H"

#include "../../src/cut/cut_side.H"
#include "../../src/cut/cut_meshintersection.H"
#include "../../src/cut/cut_levelsetintersection.H"
#include "../../src/cut/cut_combintersection.H"
#include "../../src/cut/cut_tetmeshintersection.H"
#include "../../src/cut/cut_options.H"
#include "../../src/cut/cut_volumecell.H"

#include "../../src/fem_general/utils_local_connectivity_matrices.H"

void test_generated_40()
{
  Cut::MeshIntersection intersection;
  intersection.GetOptions().Init_for_Cuttests();  // use full cln
  std::vector<int> nids;

  int sidecount = 0;
  std::vector<double> lsvs(8);
  {
    Core::LinAlg::SerialDenseMatrix tri3_xyze( 3, 3 );

    nids.clear();
    tri3_xyze(0,0) = 2.7755575615628913511e-17;
    tri3_xyze(1,0) = -0.35355339059327373086;
    tri3_xyze(2,0) = -0.02999999999999999889;
    nids.push_back( 4 );
    tri3_xyze(0,1) = 0.17677669529663689318;
    tri3_xyze(1,1) = -0.17677669529663686543;
    tri3_xyze(2,1) = -0.02999999999999999889;
    nids.push_back( 14 );
    tri3_xyze(0,2) = 0.08838834764831846047;
    tri3_xyze(1,2) = -0.26516504294495529814;
    tri3_xyze(2,2) = 0;
    nids.push_back( -5 );
    intersection.AddCutSide( ++sidecount, nids, tri3_xyze, Core::FE::CellType::tri3 );
  }
  {
    Core::LinAlg::SerialDenseMatrix tri3_xyze( 3, 3 );

    nids.clear();
    tri3_xyze(0,0) = 0.17677669529663689318;
    tri3_xyze(1,0) = -0.17677669529663686543;
    tri3_xyze(2,0) = 0.02999999999999999889;
    nids.push_back( 64 );
    tri3_xyze(0,1) = 2.7755575615628913511e-17;
    tri3_xyze(1,1) = -0.35355339059327373086;
    tri3_xyze(2,1) = 0.02999999999999999889;
    nids.push_back( 54 );
    tri3_xyze(0,2) = 0.08838834764831846047;
    tri3_xyze(1,2) = -0.26516504294495529814;
    tri3_xyze(2,2) = 0;
    nids.push_back( -5 );
    intersection.AddCutSide( ++sidecount, nids, tri3_xyze, Core::FE::CellType::tri3 );
  }
  {
    Core::LinAlg::SerialDenseMatrix tri3_xyze( 3, 3 );

    nids.clear();
    tri3_xyze(0,0) = 2.7755575615628913511e-17;
    tri3_xyze(1,0) = -0.35355339059327373086;
    tri3_xyze(2,0) = 0.02999999999999999889;
    nids.push_back( 54 );
    tri3_xyze(0,1) = 2.7755575615628913511e-17;
    tri3_xyze(1,1) = -0.35355339059327373086;
    tri3_xyze(2,1) = -0.02999999999999999889;
    nids.push_back( 4 );
    tri3_xyze(0,2) = 0.08838834764831846047;
    tri3_xyze(1,2) = -0.26516504294495529814;
    tri3_xyze(2,2) = 0;
    nids.push_back( -5 );
    intersection.AddCutSide( ++sidecount, nids, tri3_xyze, Core::FE::CellType::tri3 );
  }
  {
  LinAlg::SerialDenseMatrix hex8_xyze( 3, 8 );

    nids.clear();
  hex8_xyze(0,0) = -0.0625;
  hex8_xyze(1,0) = -0.375;
  hex8_xyze(2,0) = -0.02999999999999999889;
  nids.push_back( 221 );
  hex8_xyze(0,1) = 0;
  hex8_xyze(1,1) = -0.375;
  hex8_xyze(2,1) = -0.02999999999999999889;
  nids.push_back( 223 );
  hex8_xyze(0,2) = 0;
  hex8_xyze(1,2) = -0.3125;
  hex8_xyze(2,2) = -0.02999999999999999889;
  nids.push_back( 289 );
  hex8_xyze(0,3) = -0.0625;
  hex8_xyze(1,3) = -0.3125;
  hex8_xyze(2,3) = -0.02999999999999999889;
  nids.push_back( 287 );
  hex8_xyze(0,4) = -0.0625;
  hex8_xyze(1,4) = -0.375;
  hex8_xyze(2,4) = 0.02999999999999999889;
  nids.push_back( 2399 );
  hex8_xyze(0,5) = 0;
  hex8_xyze(1,5) = -0.375;
  hex8_xyze(2,5) = 0.02999999999999999889;
  nids.push_back( 2401 );
  hex8_xyze(0,6) = 0;
  hex8_xyze(1,6) = -0.3125;
  hex8_xyze(2,6) = 0.02999999999999999889;
  nids.push_back( 2467 );
  hex8_xyze(0,7) = -0.0625;
  hex8_xyze(1,7) = -0.3125;
  hex8_xyze(2,7) = 0.02999999999999999889;
  nids.push_back( 2465 );

  intersection.add_element( 39, nids, hex8_xyze, Core::FE::CellType::hex8);
  }

  {
  LinAlg::SerialDenseMatrix hex8_xyze( 3, 8 );

    nids.clear();
  hex8_xyze(0,0) = 0;
  hex8_xyze(1,0) = -0.375;
  hex8_xyze(2,0) = -0.02999999999999999889;
  nids.push_back( 223 );
  hex8_xyze(0,1) = 0.0625;
  hex8_xyze(1,1) = -0.375;
  hex8_xyze(2,1) = -0.02999999999999999889;
  nids.push_back( 225 );
  hex8_xyze(0,2) = 0.0625;
  hex8_xyze(1,2) = -0.3125;
  hex8_xyze(2,2) = -0.02999999999999999889;
  nids.push_back( 291 );
  hex8_xyze(0,3) = 0;
  hex8_xyze(1,3) = -0.3125;
  hex8_xyze(2,3) = -0.02999999999999999889;
  nids.push_back( 289 );
  hex8_xyze(0,4) = 0;
  hex8_xyze(1,4) = -0.375;
  hex8_xyze(2,4) = 0.02999999999999999889;
  nids.push_back( 2401 );
  hex8_xyze(0,5) = 0.0625;
  hex8_xyze(1,5) = -0.375;
  hex8_xyze(2,5) = 0.02999999999999999889;
  nids.push_back( 2403 );
  hex8_xyze(0,6) = 0.0625;
  hex8_xyze(1,6) = -0.3125;
  hex8_xyze(2,6) = 0.02999999999999999889;
  nids.push_back( 2469 );
  hex8_xyze(0,7) = 0;
  hex8_xyze(1,7) = -0.3125;
  hex8_xyze(2,7) = 0.02999999999999999889;
  nids.push_back( 2467 );

  intersection.add_element( 40, nids, hex8_xyze, Core::FE::CellType::hex8);
  }

  {
  LinAlg::SerialDenseMatrix hex8_xyze( 3, 8 );

    nids.clear();
  hex8_xyze(0,0) = 0.0625;
  hex8_xyze(1,0) = -0.375;
  hex8_xyze(2,0) = -0.02999999999999999889;
  nids.push_back( 225 );
  hex8_xyze(0,1) = 0.125;
  hex8_xyze(1,1) = -0.375;
  hex8_xyze(2,1) = -0.02999999999999999889;
  nids.push_back( 227 );
  hex8_xyze(0,2) = 0.125;
  hex8_xyze(1,2) = -0.3125;
  hex8_xyze(2,2) = -0.02999999999999999889;
  nids.push_back( 293 );
  hex8_xyze(0,3) = 0.0625;
  hex8_xyze(1,3) = -0.3125;
  hex8_xyze(2,3) = -0.02999999999999999889;
  nids.push_back( 291 );
  hex8_xyze(0,4) = 0.0625;
  hex8_xyze(1,4) = -0.375;
  hex8_xyze(2,4) = 0.02999999999999999889;
  nids.push_back( 2403 );
  hex8_xyze(0,5) = 0.125;
  hex8_xyze(1,5) = -0.375;
  hex8_xyze(2,5) = 0.02999999999999999889;
  nids.push_back( 2405 );
  hex8_xyze(0,6) = 0.125;
  hex8_xyze(1,6) = -0.3125;
  hex8_xyze(2,6) = 0.02999999999999999889;
  nids.push_back( 2471 );
  hex8_xyze(0,7) = 0.0625;
  hex8_xyze(1,7) = -0.3125;
  hex8_xyze(2,7) = 0.02999999999999999889;
  nids.push_back( 2469 );

  intersection.add_element( 41, nids, hex8_xyze, Core::FE::CellType::hex8);
  }

  {
  LinAlg::SerialDenseMatrix hex8_xyze( 3, 8 );

    nids.clear();
  hex8_xyze(0,0) = 0;
  hex8_xyze(1,0) = -0.3125;
  hex8_xyze(2,0) = -0.02999999999999999889;
  nids.push_back( 289 );
  hex8_xyze(0,1) = 0.0625;
  hex8_xyze(1,1) = -0.3125;
  hex8_xyze(2,1) = -0.02999999999999999889;
  nids.push_back( 291 );
  hex8_xyze(0,2) = 0.0625;
  hex8_xyze(1,2) = -0.25;
  hex8_xyze(2,2) = -0.02999999999999999889;
  nids.push_back( 357 );
  hex8_xyze(0,3) = 0;
  hex8_xyze(1,3) = -0.25;
  hex8_xyze(2,3) = -0.02999999999999999889;
  nids.push_back( 355 );
  hex8_xyze(0,4) = 0;
  hex8_xyze(1,4) = -0.3125;
  hex8_xyze(2,4) = 0.02999999999999999889;
  nids.push_back( 2467 );
  hex8_xyze(0,5) = 0.0625;
  hex8_xyze(1,5) = -0.3125;
  hex8_xyze(2,5) = 0.02999999999999999889;
  nids.push_back( 2469 );
  hex8_xyze(0,6) = 0.0625;
  hex8_xyze(1,6) = -0.25;
  hex8_xyze(2,6) = 0.02999999999999999889;
  nids.push_back( 2535 );
  hex8_xyze(0,7) = 0;
  hex8_xyze(1,7) = -0.25;
  hex8_xyze(2,7) = 0.02999999999999999889;
  nids.push_back( 2533 );

  intersection.add_element( 56, nids, hex8_xyze, Core::FE::CellType::hex8);
  }

  intersection.CutTest_Cut( true,Cut::VCellGaussPts_DirectDivergence, Cut::BCellGaussPts_Tessellation );
  intersection.Cut_Finalize( true, Cut::VCellGaussPts_DirectDivergence, Cut::BCellGaussPts_Tessellation, false, true );

}
