"""The probe grid a task ASKS for must be the one the grader ACCEPTS.

WHY THIS EXISTS
---------------
`grade_blind.grade_run` calls `matches_probe_grid(pts, probe_grid(dim))` and
returns INVALID_SUBMISSION when the agent's CSV does not land on the grader's
own grid. That grid is `PROBE_M = {2: 44, 3: 21}`.

`PROBE_M` was changed from `{2: 32, 3: 16}` because the old counts were
commensurate with the mesh levels: at the finest level the probe grid had the
mesh's own spacing and sat at the midpoint of each quad's diagonal, the worst
point of the P1 interpolation error, biasing the observed order down by 0.27 —
two thirds of the tolerance budget. The measurements are recorded above the
constant in grade_blind.py.

The coupled family (D1-D8) is GENERATED by build_coupled_v2.py, which imports
the same constant, so it followed the change. The single-code family (B1-B7) is
a set of committed text files that nothing regenerates, so it did not. For some
time B1-B7 asked for 1024 points at (i+0.5)/32 (2D) and 4096 at (i+0.5)/16 (3D)
while the grader demanded 1936 at /44 and 9261 at /21.

Nothing detected it. Every B submission would have been graded
INVALID_SUBMISSION on arrival — not for anything the model did, but because the
instructions and the marking scheme disagreed. A campaign run in that state
produces a table of zeros that looks like a finding about model capability.

This test makes the two definitions the same fact. If `PROBE_M` moves again,
this fails until the task texts move with it.

WHAT IT DOES NOT CHECK
----------------------
It does not check that the grid is a GOOD one — that judgement lives in
`assert_probe_grid_incommensurate` and in the bias table in grade_blind.py.
It checks only that the task text and the grader agree, which is the failure
that actually happened.
"""
from __future__ import annotations

import importlib.util
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PROBLEMS = REPO / "campaign3_blind" / "problems"
GRADER = REPO / "campaign3_blind" / "grade_blind.py"

_PROBE_LINE = re.compile(
    r"the (?P<count>\d+) points given by x = \(i_x\+0\.5\)/(?P<m>\d+)")


def _grader():
    spec = importlib.util.spec_from_file_location("gb", GRADER)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _tasks_with_a_uniform_probe_grid():
    """The single-code tasks. Coupled tasks state per-subdomain grids that are
    scaled to each subdomain's extent, so they are checked by their generator
    rather than by this regex."""
    for d in sorted(PROBLEMS.iterdir()):
        f = d / "task.txt"
        if not f.is_file():
            continue
        txt = f.read_text(encoding="utf-8")
        m = _PROBE_LINE.search(txt)
        if m and "subdomain" not in txt.split("PROBE POINTS")[1][:40]:
            yield d.name, txt, m


def test_every_task_asks_for_the_grid_the_grader_accepts() -> None:
    gb = _grader()
    wrong = []
    for name, txt, m in _tasks_with_a_uniform_probe_grid():
        dim = 3 if "(i_z+0.5)" in txt else 2
        stated_m = int(m.group("m"))
        stated_count = int(m.group("count"))
        want_m = gb.PROBE_M[dim]
        if stated_m != want_m or stated_count != want_m ** dim:
            wrong.append(
                f"{name}: task asks for {stated_count} points at "
                f"(i+0.5)/{stated_m}, grader accepts only {want_m ** dim} at "
                f"(i+0.5)/{want_m}")
    assert not wrong, (
        "task text and grader disagree about the probe grid, so these "
        "submissions grade INVALID_SUBMISSION however good the solution is:"
        "\n    " + "\n    ".join(wrong)
        + "\n\nPROBE_M in grade_blind.py is the single source of truth; update "
          "the task texts to match it.")


_COUPLED_LINE = re.compile(
    r"PROBE POINTS, subdomain (?P<side>[AB]): the (?P<count>\d+) points"
    r"(?P<rest>[^\n]*)")
# A non-rectangular subdomain states the full grid, then the exclusion, then
# how many points survive it. The surviving count is the operative one — it is
# what the agent is told to write and what the grader must build.
_REMAIN = re.compile(r"(\d+) points remain")


def test_coupled_tasks_state_the_count_the_grader_builds() -> None:
    """The count printed in a coupled task must equal the grader's grid for
    that subdomain, exclusions included.

    D5's subdomain A is the unit square minus subdomain B minus a notch. Its
    task text says so and states 1331 points. The grader built the full
    1936-point rectangle because nothing applied `probe_a_exclude`, so a
    submission that followed the task exactly was rejected as
    INVALID_SUBMISSION. This checks the two agree for every side of every
    coupled problem, not just the rectangular ones.
    """
    gb = _grader()
    wrong = []
    for d in sorted(PROBLEMS.iterdir()):
        task, spec_f = d / "task.txt", d / "spec_public.json"
        if not (task.is_file() and spec_f.is_file()):
            continue
        txt = task.read_text(encoding="utf-8")
        import json
        spec = json.loads(spec_f.read_text())
        dim = spec.get("dim", 2)
        for m in _COUPLED_LINE.finditer(txt):
            side = m.group("side")
            remain = _REMAIN.search(m.group("rest"))
            stated = int(remain.group(1) if remain else m.group("count"))
            extent = spec.get(f"extent_{side.lower()}")
            if not extent:
                continue
            bounds = [tuple(a) for a in extent]
            built = len(gb.probe_grid(
                dim, bounds, gb.probe_exclusions(d.name, side)))
            if built != stated:
                wrong.append(
                    f"{d.name} subdomain {side}: task states {stated} points, "
                    f"grader builds {built}")
    assert not wrong, (
        "coupled task text and grader disagree on the probe count, so these "
        "grade INVALID_SUBMISSION however good the solution is:\n    "
        + "\n    ".join(wrong))


def test_the_stated_grid_reproduces_the_graders_points() -> None:
    """Stronger than comparing numbers: build the point set the task describes
    and hand it to the grader's own acceptance check."""
    gb = _grader()
    bad = []
    for name, txt, m in _tasks_with_a_uniform_probe_grid():
        dim = 3 if "(i_z+0.5)" in txt else 2
        M = int(m.group("m"))
        axis = [(i + 0.5) / M for i in range(M)]
        pts = [()]
        for _ in range(dim):
            pts = [p + (v,) for p in pts for v in axis]
        good, why = gb.matches_probe_grid(pts, gb.probe_grid(dim))
        if not good:
            bad.append(f"{name}: {why}")
    assert not bad, (
        "the points a task describes are rejected by the grader:\n    "
        + "\n    ".join(bad))
