"""
preCICE coupling — a first-class member of OASiS.

preCICE (precice.org) is the field-standard library for black-box coupling of
independent simulation codes. In OASiS it is the native coupling path for genuinely
forced multi-paradigm couplings — e.g. a DSMC particle code (SPARTA) coupled to a FEM
solid (FEniCS) for conjugate heat transfer — that the file-handshake driver cannot
express as cleanly.

This module (1) detects the preCICE Python bindings + C++ library, (2) generates valid
preCICE-config.xml for standard coupling scenarios (heat DN, TSI, and generic), and
(3) verifies an end-to-end coupling actually runs. The libprecice shared library lives
at PRECICE_LIB_DIR (default /opt/precice/lib); pyprecice must match its version.
"""

import logging
import os
from pathlib import Path

logger = logging.getLogger("oasis.precice")

# Location of libprecice.so.* — pyprecice loads it at import time.
PRECICE_LIB_DIR = os.environ.get("PRECICE_LIB_DIR", "/opt/precice/lib")


def _ensure_lib_on_path() -> None:
    """Make libprecice loadable for the pyprecice import.

    Sets LD_LIBRARY_PATH (for child processes) AND ctypes-preloads libprecice into the
    current process with RTLD_GLOBAL — necessary because changing LD_LIBRARY_PATH at
    runtime does NOT affect the already-initialized dynamic linker of this process.
    """
    if not Path(PRECICE_LIB_DIR).exists():
        return
    cur = os.environ.get("LD_LIBRARY_PATH", "")
    if PRECICE_LIB_DIR not in cur.split(":"):
        os.environ["LD_LIBRARY_PATH"] = (PRECICE_LIB_DIR + ":" + cur).rstrip(":")
    import ctypes
    for cand in ("libprecice.so.3", "libprecice.so"):
        try:
            ctypes.CDLL(str(Path(PRECICE_LIB_DIR) / cand), mode=ctypes.RTLD_GLOBAL)
            return
        except OSError:
            continue


def check_precice_available() -> tuple[bool, str]:
    """Check that the preCICE Python bindings + C++ library are usable.

    Returns (ok, message). Sets LD_LIBRARY_PATH so the bindings can find libprecice.
    """
    _ensure_lib_on_path()
    try:
        import precice
        info = precice.get_version_information()
        ver = info.decode().split(";")[0] if isinstance(info, bytes) else str(info)
        return True, f"preCICE {ver} (lib at {PRECICE_LIB_DIR})"
    except ImportError as e:
        return False, (
            f"preCICE Python bindings not importable ({e}). Install a pyprecice whose "
            f"version matches libprecice in {PRECICE_LIB_DIR}: pip install 'pyprecice==<libver>'"
        )
    except Exception as e:
        return False, f"preCICE present but unusable: {e}"


def generate_heat_coupling_config(
    mesh_name_a: str = "FEniCS-Mesh",
    mesh_name_b: str = "4C-Mesh",
    data_name: str = "Temperature",
    flux_name: str = "Heat-Flux",
    max_iterations: int = 20,
    convergence_tol: float = 1e-6,
    relaxation: float = 0.5,
    time_window: float = 1.0,
    output_dir: str = "precice-output",
) -> str:
    """Generate preCICE XML config for Dirichlet-Neumann heat coupling.

    This produces a configuration equivalent to our MCP-orchestrated DN
    domain decomposition, enabling direct comparison.

    Args:
        mesh_name_a: Mesh name for the Dirichlet participant (FEniCS).
        mesh_name_b: Mesh name for the Neumann participant (4C).
        data_name: Name of the temperature data field.
        flux_name: Name of the heat flux data field.
        max_iterations: Maximum implicit coupling iterations.
        convergence_tol: Convergence criterion for the coupling.
        relaxation: Initial relaxation factor for Aitken acceleration.
        time_window: Size of coupling time window.
        output_dir: Directory for preCICE output.

    Returns:
        Complete preCICE XML configuration as a string.
    """
    return f"""\
<?xml version="1.0" encoding="UTF-8" ?>
<precice-configuration>
  <!-- preCICE config for DN heat coupling — generated by OASiS -->

  <log>
    <sink type="stream" output="stdout" filter="%Severity% > debug"
          format="%ColorizedSeverity% %Message%" enabled="true" />
  </log>

  <data:scalar name="{data_name}" />
  <data:scalar name="{flux_name}" />

  <mesh name="{mesh_name_a}" dimensions="2">
    <use-data name="{data_name}" />
    <use-data name="{flux_name}" />
  </mesh>

  <mesh name="{mesh_name_b}" dimensions="2">
    <use-data name="{data_name}" />
    <use-data name="{flux_name}" />
  </mesh>

  <!-- Dirichlet participant (FEniCS): writes temperature, reads flux -->
  <participant name="Dirichlet">
    <provide-mesh name="{mesh_name_a}" />
    <receive-mesh name="{mesh_name_b}" from="Neumann" />
    <write-data name="{data_name}" mesh="{mesh_name_a}" />
    <read-data name="{flux_name}" mesh="{mesh_name_a}" />
    <mapping:nearest-neighbor direction="read"
      from="{mesh_name_b}" to="{mesh_name_a}"
      constraint="consistent" />
  </participant>

  <!-- Neumann participant (4C): reads temperature, writes flux -->
  <participant name="Neumann">
    <provide-mesh name="{mesh_name_b}" />
    <receive-mesh name="{mesh_name_a}" from="Dirichlet" />
    <write-data name="{flux_name}" mesh="{mesh_name_b}" />
    <read-data name="{data_name}" mesh="{mesh_name_b}" />
    <mapping:nearest-neighbor direction="read"
      from="{mesh_name_a}" to="{mesh_name_b}"
      constraint="consistent" />
  </participant>

  <m2n:sockets acceptor="Dirichlet" connector="Neumann"
    exchange-directory=".." />

  <coupling-scheme:serial-implicit>
    <time-window-size value="{time_window}" />
    <max-time value="{time_window}" />
    <participants first="Dirichlet" second="Neumann" />
    <exchange data="{data_name}" mesh="{mesh_name_a}"
      from="Dirichlet" to="Neumann" />
    <exchange data="{flux_name}" mesh="{mesh_name_b}"
      from="Neumann" to="Dirichlet" />
    <max-iterations value="{max_iterations}" />
    <relative-convergence-measure limit="{convergence_tol}"
      data="{data_name}" mesh="{mesh_name_a}" />
    <acceleration:aitken>
      <data mesh="{mesh_name_a}" name="{data_name}" />
      <initial-relaxation value="{relaxation}" />
    </acceleration:aitken>
  </coupling-scheme:serial-implicit>
</precice-configuration>
"""


def generate_tsi_coupling_config(
    mesh_name_a: str = "Thermal-Mesh",
    mesh_name_b: str = "Structure-Mesh",
    temperature_name: str = "Temperature",
    displacement_name: str = "Displacement",
    heat_flux_name: str = "Heat-Flux",
    traction_name: str = "Force",
    max_iterations: int = 30,
    convergence_tol: float = 1e-6,
    time_window: float = 1.0,
) -> str:
    """Generate preCICE XML for thermal-structural interaction coupling.

    Two-way coupling: temperature and displacement exchanged between solvers.

    Returns:
        Complete preCICE XML configuration string.
    """
    return f"""\
<?xml version="1.0" encoding="UTF-8" ?>
<precice-configuration>
  <!-- preCICE config for TSI coupling — generated by OASiS -->

  <log>
    <sink type="stream" output="stdout" filter="%Severity% > debug"
          format="%ColorizedSeverity% %Message%" enabled="true" />
  </log>

  <data:scalar name="{temperature_name}" />
  <data:vector name="{displacement_name}" />
  <data:scalar name="{heat_flux_name}" />

  <mesh name="{mesh_name_a}" dimensions="3">
    <use-data name="{temperature_name}" />
    <use-data name="{heat_flux_name}" />
  </mesh>

  <mesh name="{mesh_name_b}" dimensions="3">
    <use-data name="{temperature_name}" />
    <use-data name="{displacement_name}" />
  </mesh>

  <!-- Thermal solver: provides temperature, receives heat flux -->
  <participant name="Thermal">
    <provide-mesh name="{mesh_name_a}" />
    <receive-mesh name="{mesh_name_b}" from="Structure" />
    <write-data name="{temperature_name}" mesh="{mesh_name_a}" />
    <read-data name="{heat_flux_name}" mesh="{mesh_name_a}" />
    <mapping:nearest-neighbor direction="read"
      from="{mesh_name_b}" to="{mesh_name_a}"
      constraint="consistent" />
  </participant>

  <!-- Structural solver: reads temperature, provides displacement -->
  <participant name="Structure">
    <provide-mesh name="{mesh_name_b}" />
    <receive-mesh name="{mesh_name_a}" from="Thermal" />
    <read-data name="{temperature_name}" mesh="{mesh_name_b}" />
    <write-data name="{displacement_name}" mesh="{mesh_name_b}" />
    <mapping:nearest-neighbor direction="read"
      from="{mesh_name_a}" to="{mesh_name_b}"
      constraint="consistent" />
  </participant>

  <m2n:sockets acceptor="Thermal" connector="Structure"
    exchange-directory=".." />

  <coupling-scheme:serial-implicit>
    <time-window-size value="{time_window}" />
    <max-time value="{time_window}" />
    <participants first="Thermal" second="Structure" />
    <exchange data="{temperature_name}" mesh="{mesh_name_a}"
      from="Thermal" to="Structure" />
    <exchange data="{displacement_name}" mesh="{mesh_name_b}"
      from="Structure" to="Thermal" />
    <max-iterations value="{max_iterations}" />
    <relative-convergence-measure limit="{convergence_tol}"
      data="{temperature_name}" mesh="{mesh_name_a}" />
    <acceleration:aitken>
      <data mesh="{mesh_name_a}" name="{temperature_name}" />
      <initial-relaxation value="0.5" />
    </acceleration:aitken>
  </coupling-scheme:serial-implicit>
</precice-configuration>
"""


def save_precice_config(config_xml: str, output_dir: Path, filename: str = "precice-config.xml") -> Path:
    """Save preCICE configuration to file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / filename
    path.write_text(config_xml)
    logger.info(f"preCICE config saved to {path}")
    return path


# A minimal two-participant preCICE config used to verify the coupling end-to-end.
_VERIFY_CONFIG = """\
<?xml version="1.0" encoding="UTF-8" ?>
<precice-configuration>
  <data:scalar name="Val" />
  <mesh name="A-Mesh" dimensions="2"><use-data name="Val" /></mesh>
  <mesh name="B-Mesh" dimensions="2"><use-data name="Val" /></mesh>
  <participant name="A">
    <provide-mesh name="A-Mesh" />
    <write-data name="Val" mesh="A-Mesh" />
  </participant>
  <participant name="B">
    <provide-mesh name="B-Mesh" />
    <receive-mesh name="A-Mesh" from="A" />
    <read-data name="Val" mesh="B-Mesh" />
    <mapping:nearest-neighbor direction="read" from="A-Mesh" to="B-Mesh" constraint="consistent" />
  </participant>
  <m2n:sockets acceptor="A" connector="B" exchange-directory="." />
  <coupling-scheme:serial-explicit>
    <time-window-size value="1.0" /><max-time value="3.0" />
    <participants first="A" second="B" />
    <exchange data="Val" mesh="A-Mesh" from="A" to="B" />
  </coupling-scheme:serial-explicit>
</precice-configuration>
"""

_VERIFY_PARTICIPANT = """\
import sys, numpy as np, precice
name, other = sys.argv[1], sys.argv[2]
p = precice.Participant(name, "precice-config.xml", 0, 1)
mesh = f"{name}-Mesh"
vid = p.set_mesh_vertices(mesh, np.array([[0.0, 0.0]]))
p.initialize()
while p.is_coupling_ongoing():
    dt = p.get_max_time_step_size()
    if name == "B":
        v = p.read_data(mesh, "Val", vid, dt)
        print(f"B received {float(v[0])}", flush=True)
    if name == "A":
        p.write_data(mesh, "Val", vid, np.array([42.0]))
    p.advance(dt)
p.finalize()
"""


def verify_precice_coupling(work_dir: Path = None, timeout: int = 60) -> tuple[bool, str]:
    """Run a real 2-participant preCICE coupling and confirm data is exchanged.

    Launches participants A and B (A writes 42.0, B reads it) over 3 time windows via
    the preCICE sockets m2n. Returns (ok, message). This is the complete end-to-end
    verification that preCICE works in this environment, not just that it imports.
    """
    import subprocess, sys, tempfile, time
    _ensure_lib_on_path()
    wd = Path(work_dir or tempfile.mkdtemp(prefix="precice_verify_"))
    wd.mkdir(parents=True, exist_ok=True)
    (wd / "precice-config.xml").write_text(_VERIFY_CONFIG)
    (wd / "participant.py").write_text(_VERIFY_PARTICIPANT)
    env = os.environ.copy()
    env["LD_LIBRARY_PATH"] = PRECICE_LIB_DIR + ":" + env.get("LD_LIBRARY_PATH", "")
    py = sys.executable
    try:
        pa = subprocess.Popen([py, "participant.py", "A", "B"], cwd=wd, env=env,
                              stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        pb = subprocess.Popen([py, "participant.py", "B", "A"], cwd=wd, env=env,
                              stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        out_b, _ = pb.communicate(timeout=timeout)
        pa.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        pa.kill(); pb.kill()
        return False, "preCICE coupling timed out (deadlock?)"
    except Exception as e:
        return False, f"preCICE coupling launch failed: {e}"
    got = out_b.count("B received 42.0")
    if pa.returncode == 0 and pb.returncode == 0 and got >= 1:
        return True, f"preCICE coupling verified: B received the coupled value over {got} window(s)"
    return False, f"preCICE coupling failed (rc_A={pa.returncode}, rc_B={pb.returncode}); output:\n{out_b[-500:]}"
