"""Cross-backend Table-1 + Tier-2 inventory.

Generates ``scripts/scan_results/cross_backend_inventory.json``
and a markdown summary. Useful as a tracked snapshot of overall
audit progress — committed to the repo so the trajectory across
iterations is visible.

Columns:
  * Total      — pitfalls returned by backend.get_knowledge()
                 across every physics in supported_physics()
  * Table-1    — entries with a Signal: clause (the
                 falsifiability format)
  * Tier-0+1   — entries that pass both falsifiability gates
                 (Signal references a real code symbol AND
                 uses observable-symptom vocabulary)
  * Tier-2     — entries with a passing operational fixture
                 (catalog-indexed, not synthetic)
  * Gameable   — entries scoring Tier-0 by domain-name match
                 only (the forbidden mode the round-2 critic
                 flagged). MUST be 0 across all promoted
                 backends.

Usage:
    python3 scripts/cross_backend_inventory.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))


def main() -> int:
    from verify_signal_clauses import verify_backend
    backends = ["dealii", "kratos", "fenics", "ngsolve",
                "skfem", "dune", "fourc"]
    rows = []
    total = {"n": 0, "t1": 0, "t01": 0, "t2": 0, "gm": 0}
    for be in backends:
        try:
            results = verify_backend(be)
        except Exception:
            continue
        n = len(results)
        t1 = sum(1 for r in results if r.signal_text)
        t01 = sum(1 for r in results
                  if r.tier0_passed and r.tier1_passed)
        t2 = sum(1 for r in results if r.tier2_passed)
        gm = sum(1 for r in results
                 if r.tier0_domain_names_matched
                 and not r.tier0_code_symbol_matched)
        rows.append({
            "backend": be,
            "total": n,
            "table1": t1,
            "tier0_and_1": t01,
            "tier2_catalog_indexed": t2,
            "gameable": gm,
        })
        for k, v in (("n", n), ("t1", t1), ("t01", t01),
                      ("t2", t2), ("gm", gm)):
            total[k] += v

    snapshot = {
        "_comment": ("Audit inventory: catalog Table-1 promotion + "
                     "Tier-2 fixture coverage by backend. "
                     "Generated by scripts/cross_backend_inventory.py."),
        "rows": rows,
        "total": {
            "total_pitfalls": total["n"],
            "table1": total["t1"],
            "tier0_and_1": total["t01"],
            "tier2_catalog_indexed": total["t2"],
            "gameable": total["gm"],
        },
    }
    out = REPO_ROOT / "scripts" / "scan_results" / "cross_backend_inventory.json"
    out.write_text(json.dumps(snapshot, indent=2))
    print(f"inventory written: {out}\n")

    # Print summary table.
    print(f"{'Backend':10s} {'Total':>6s} {'Table-1':>9s} "
          f"{'Tier-0+1':>10s} {'Tier-2':>8s} {'Gameable':>10s}")
    print("-" * 60)
    for r in rows:
        print(f"{r['backend']:10s} {r['total']:>6} "
              f"{r['table1']:>9} {r['tier0_and_1']:>10} "
              f"{r['tier2_catalog_indexed']:>8} {r['gameable']:>10}")
    print("-" * 60)
    print(f"{'TOTAL':10s} {total['n']:>6} {total['t1']:>9} "
          f"{total['t01']:>10} {total['t2']:>8} {total['gm']:>10}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
